server:
  port: 8761

spring:
  application:
    name: discoveryservice # ????????? ??? ID? ??


eureka:
  client: # ???? ???? ???, ????? ?? off
    register-with-eureka: false
    fetch-registry: false